// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Thermostat_M5

#ifndef _THERMOSTAT_M5_UI_H
#define _THERMOSTAT_M5_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Header;
extern lv_obj_t *ui_Header_Date;
extern lv_obj_t *ui_Header_Time;
extern lv_obj_t *ui_Arc_Group;
extern lv_obj_t *ui_Label2;
void ui_event_Arc1( lv_event_t * e);
extern lv_obj_t *ui_Arc1;
extern lv_obj_t *ui_Label_Celsius;
void ui_event_Fan_Speed_Control( lv_event_t * e);
extern lv_obj_t *ui_Fan_Speed_Control;
extern lv_obj_t *ui_Label_Slider;
void ui_event_Button1a( lv_event_t * e);
extern lv_obj_t *ui_Button1a;
void ui_event_Button1b( lv_event_t * e);
extern lv_obj_t *ui_Button1b;
void ui_event_Button1c( lv_event_t * e);
extern lv_obj_t *ui_Button1c;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t *ui_Screen2;
void ui_event_Button2a( lv_event_t * e);
extern lv_obj_t *ui_Button2a;
void ui_event_Button2b( lv_event_t * e);
extern lv_obj_t *ui_Button2b;
void ui_event_Button2c( lv_event_t * e);
extern lv_obj_t *ui_Button2c;
extern lv_obj_t *ui_Image1;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t *ui_Screen3;
void ui_event_Button3a( lv_event_t * e);
extern lv_obj_t *ui_Button3a;
void ui_event_Button3b( lv_event_t * e);
extern lv_obj_t *ui_Button3b;
void ui_event_Button3c( lv_event_t * e);
extern lv_obj_t *ui_Button3c;
extern lv_obj_t *ui_Bar1;
extern lv_obj_t *ui_Header1;
extern lv_obj_t *ui_Header_Title;
extern lv_obj_t *ui_Header_Time1;
extern lv_obj_t *ui_Bar2;
extern lv_obj_t *ui_Bar3;
extern lv_obj_t *ui_Bar4;
extern lv_obj_t *ui_LabelRSSI;
extern lv_obj_t *ui_LabelBand;
extern lv_obj_t *ui_LabelRat;
extern lv_obj_t *ui_LabelConnected;
extern lv_obj_t *ui_LabelSerial;
extern lv_obj_t *ui_LabelSyncStatus;
extern lv_obj_t *ui_LabelDevice;
extern lv_obj_t *ui_LabelHubStatus;
extern lv_obj_t *ui_TextAreaSyncStatus;
extern lv_obj_t *ui_TextAreaHubStatus;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_pngwing_com_png);   // assets/pngwing.com.png

LV_FONT_DECLARE( ui_font_Number);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
