// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Thermostat_M5

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button2a = lv_btn_create(ui_Screen2);
lv_obj_set_width( ui_Button2a, 100);
lv_obj_set_height( ui_Button2a, 40);
lv_obj_set_x( ui_Button2a, -105 );
lv_obj_set_y( ui_Button2a, 0 );
lv_obj_set_align( ui_Button2a, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_Button2a, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button2a, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Button2a, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button2a, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Button2a, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button2a, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button2b = lv_btn_create(ui_Screen2);
lv_obj_set_width( ui_Button2b, 100);
lv_obj_set_height( ui_Button2b, 40);
lv_obj_set_align( ui_Button2b, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_Button2b, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button2b, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button2c = lv_btn_create(ui_Screen2);
lv_obj_set_width( ui_Button2c, 100);
lv_obj_set_height( ui_Button2c, 40);
lv_obj_set_x( ui_Button2c, 105 );
lv_obj_set_y( ui_Button2c, 0 );
lv_obj_set_align( ui_Button2c, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_Button2c, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button2c, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image1 = lv_img_create(ui_Screen2);
lv_img_set_src(ui_Image1, &ui_img_pngwing_com_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_Button2a, ui_event_Button2a, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button2b, ui_event_Button2b, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button2c, ui_event_Button2c, LV_EVENT_ALL, NULL);

}
